"""new fields in user model

Revision ID: 608d5b7187d9
Revises: d7fb34e36a40
Create Date: 2019-12-11 01:23:32.066113

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '608d5b7187d9'
down_revision = 'd7fb34e36a40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
